---
# A simple Ansible setup

- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Ensure appropriate locale is set
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Update all packages to the latest version
      apt:
        update_cache: yes

    - name: Installing python3-pip and nginx
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pip
        - nginx

    - name: Configuring nginx startup service
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Cloning app repository
      git:
        repo: https://github.com/indungu/yummy-rest.git
        dest: /home/ubuntu/yummy-rest
        update: yes

    - name: Installing up virtualenv
      command: pip3 install virtualenv
      
    - name: Creating virtualenv
      command: virtualenv /home/ubuntu/yummy-venv

    - name: Initializing virtual environment
      pip:
        requirements: /home/ubuntu/yummy-rest/requirements.txt
        virtualenv: /home/ubuntu/yummy-venv

    - name: Creating environment setup file
      shell:
        chdir: /home/ubuntu/
        creates: .env
        cmd: |
          bash -c 'cat > /home/ubuntu/.env << EOF
            export DATABASE_URL="postgres://budufkitteymek:095f0029056c313190744c68ca69d19a2e315483bc41e059b40d6d9fdccf2599@ec2-107-22-229-213.compute-1.amazonaws.com:5432/d2r8p5ai580nqq"
            export APP_CONFIG="production"
            export SECRET_KEY="mYd3rTyL!tTl#sEcR3t"
            export FLASK_APP=run.py
          EOF'

    - name: Creating App Launch Script
      shell: |
        bash -c 'cat > /home/ubuntu/launch.sh << EOF
          source /home/ubuntu/.env
          source /home/ubuntu/yummy-venv/bin/activate
          gunicorn --chdir /home/ubuntu/yummy-rest --bind 0.0.0.0:8000 app:APP
        EOF'
        chmod 744 /home/ubuntu/launch.sh
    
    - name: Removing default Nginx Sites Configuration
      shell: |
        rm -f /etc/nginx/sites-available/default
        rm -f /etc/nginx/sites-enabled/default

    - name: Adding app server site config to Nginx
      shell: |
        bash -c 'cat > /etc/nginx/sites-available/default << EOF
          server {
            listen 80 default_server;
            listen [::]:80 default_server;
            server_name _;
            location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header HOST \$host;
              proxy_set_header X-Forwarded-Proto \$scheme;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
          }
        EOF'
        ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

    - name: Creating App startup service
      shell: |
        bash -c 'cat > /etc/systemd/system/yummy-rest.service <<EOF
            [Unit]
            Description=yummy-rest startup service
            After=network.target

            [Service]
            User=ubuntu
            ExecStart=/bin/bash /home/ubuntu/launch.sh

            [Install]
            WantedBy=multi-user.target
        EOF'
        chmod 664 /etc/systemd/system/yummy-rest.service

    - name: Configuring service to run on reboot
      service:
        name: yummy-rest
        enabled: yes
        state: started
...