---
# A simple Ansible setup

- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - setup
    - app
    - nginx
    - services
...