---
# A simple Ansible setup

- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Ensure appropriate locale is set
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Update all packages to the latest version
      apt:
        update_cache: yes

    - name: Installing NodeJS PPA
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    - name: Installing NodeJS and Nginx
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - nginx

    - name: Configuring nginx startup service
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Cloning app repository
      git:
        repo: https://github.com/indungu/yummy-react.git
        dest: /home/ubuntu/yummy-react
        update: yes

    - name: Setting up App environment
      shell:
        chdir: /home/ubuntu/yummy-react/
        cmd: |
          npm install

    - name: Creating App Launch Script
      shell: |
        bash -c 'cat > /home/ubuntu/launch.sh << EOF
          cd /home/ubuntu/yummy-react/
          npm start
        EOF'
        chmod 744 /home/ubuntu/launch.sh
    
    - name: Removing default Nginx Sites Configuration
      shell: |
        rm -f /etc/nginx/sites-available/default
        rm -f /etc/nginx/sites-enabled/default

    - name: Adding app server site config to Nginx
      shell: |
        bash -c 'cat > /etc/nginx/sites-available/default << EOF
          server {
            listen 80 default_server;
            listen [::]:80 default_server;
            server_name _;
            location / {
              proxy_pass http://127.0.0.1:3000;
              proxy_set_header HOST \$host;
              proxy_set_header X-Forwarded-Proto \$scheme;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
          }
        EOF'
        ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

    - name: Creating App startup service
      shell: |
        bash -c 'cat > /etc/systemd/system/yummy-react.service <<EOF
            [Unit]
            Description=yummy-react startup service
            After=network.target

            [Service]
            User=ubuntu
            ExecStart=/bin/bash /home/ubuntu/launch.sh

            [Install]
            WantedBy=multi-user.target
        EOF'
        chmod 664 /etc/systemd/system/yummy-react.service

    - name: Configuring service to run on reboot
      service:
        name: yummy-react
        enabled: yes
        state: started
...