---
- name: Ensure appropriate locale is set
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update all packages to the latest version
  apt:
    update_cache: yes

- name: Installing python3-pip and nginx
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - nginx
...